bee-queue/bee-queue

- README.md
- lib/defaults.js
- lib/queue.js
- lib/redis.js
- test/queue-test.js
This allows client sharing between multiple Queue instances, or other uses.
It also begins to add support for ioredis (cc #16 and #21). We might consider supporting both, though there are some major inconsistencies between the two libraries, such as the multi-exec callback form.
> Support passing redis client in settings object

- README.md
Here's my take on documenting `Queue#removeJob`, `Queue#destroy`, and `Job#remove`, as discussed in #72.
Please suggest edits if there is anything relevant I haven't touched upon.
> Document Queue#removeJob, Queue#destroy, and Job#remove

- index.d.ts
This pull request fixes two issues in the index.d.ts for the Typescript definitions.
1. The 'succeeded' event passed an error instead of a result. If the handler function ends with an error, the 'retrying'/'error' event will be called and not the 'succeeded'. 
The fix just changed the type from _Error_ to _any_.
2. The 'options' parameter in the BeeQueue constructor takes optionally a [Redis-options object](https://github.com/NodeRedis/node_redis#rediscreateclient). In the original implementation, you were very limited adding the Redis options. E.g. it was not possible to provide a Redis password which is essential in many cases. 
The fix imports the original Redis options type _ClientOpts_ from the Redis module and uses it as type for the constructor parameter 'options.redis'
> Typescript definition fix

- .travis.yml
Hopefully this will get rid of whatever strange issue #89 ran into with CI testing v6.9.1, and it'll make us test on Node 9.
> Change travis to test Node 4, 6, 8, 9 latests

- index.d.ts
> fix: DoneCallback.result is optional

- lib/queue.js
Before, the eclient was created if this was true (see line 77):
```
this.settings.getEvents || this.settings.activateDelayedJobs
```
But then it was closed iff `this.settings.getEvents` was true, which
meant that `close()` would fail to terminate all connections if the
settings were `{ getEvents: false, activateDelayedJobs: true }`.
> fix(queue): always close eclient conn if it exists

- .travis.yml
Travis CI is failing with Node 4 due to using destructuring:
```log
/home/travis/build/bee-queue/bee-queue/node_modules/eslint/lib/cli-engine.js:612
const { result, config } = processFile(fileInfo.filename, configHelper, options, this.linter);
^
SyntaxError: Unexpected token {
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/home/travis/build/bee-queue/bee-queue/node_modules/eslint/lib/cli.js:21:17)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
```
[Node 4 reached end-of-life on …
> remove node 4 test from Travis CI

- lib/queue.js
with the latest release I got a loads of warnings like this: 
```js
(node:20972) Warning: .then() only accepts functions but was passed: [object Undefined], [object Null]
```
Few minutes diving into this, it looks like bluebirdjs is printing warnings when you pass `null` in a chain `Promise.reject().catch(null)`.
> fix Bluebird promise warning spam

- index.d.ts
These types support all four call signatures:
```
close(): Promise<void>
close(timeout: number): Promise<void>;
close(cb: () => void): void;
close(timeout: number, cb: () => void): void;
```
> fix(types): account for Queue.close(timeout)

- index.d.ts
- lib/job.js
- test/queue-test.js
Per [the documentation](https://github.com/bee-queue/bee-queue#jobbackoffstrategy-delayfactor) you should be able to call `job.backoff('immediate')` to set an immediate backoff strategy for retried jobs. However, the `backoff` method explicitly disallowed this by checking for `Number.isSafeInteger(undefined)` which returns false. This means you currently cannot specify an immediate backoff strategy without also specifying a positive delay value.
To fix this, only check for valid integers when the strategy is not `immediate`.
> fix(backoff): allow no delay arg when setting immediate strategy

- README.md
I found this aspect of how bee-queue works confusing. It makes sense after reading #95 however it would be great to call it out in the README.
> add note to README about done() and process passed async function

- lib/queue.js
The error event listener is useful for catching errors from redis clients that aren't managed by the consumer of the library, but might cause problems for re-used connections.
Fixes #102 (per the extended discussion) cc @dylanjha.
> fix(queue): remove error event listener on close

- test/delay-test.js
- test/job-test.js
- test/queue-test.js
This allows use of a non-localhost Redis server.  It is necessary for the following PR which uses a non-local Redis host in a docker-compose container environment.
Regarding Docker: Not sure how to use PR base from my fork: see https://github.com/hughsw/bee-queue/pull/1  which uses docker-compose to run tests in a Docker  environment.
> feat(test/RedisHost): Use optional env BEE_QUEUE_TEST_REDIS for Redis url during testing

- index.d.ts
The Redis QueueSettings prop can accept a node_redis client object, but this wasn't reflected in the typings. If a Typescript user tried to set a RedisClient, Typescript would not compile without using `@ts-ignore`.
This PR fixes that by adding the `RedisClient` type to the `redis` prop as a union type.
> Update Redis configuration type

- README.md
- lib/job.js
- lib/queue.js
- test/queue-test.js
This feature pipelines the `EVALSHA` commands for many `Job#save` calls together to avoid the compounding latency penalty when using the `redis` library.
> feat: implement Queue#saveAll feature

- lib/lua/checkStalledJobs.lua
- test/queue-test.js
If there are many many stalled jobs, we can hit lua's built in stack limit when trying to unpack them all in the `checkStalledJobs` script. This does the unpacking in batches.
> Ensure we don't call `unpack` with too many elements

- index.d.ts
Should resolve the new errors introduced in v1.3.0 via #134.
Fixes #310.
> fix(types): fix typescript definitions errors

- README.md
A small readme update to clarify use cases for `setId(true)`. Also fixes a minor typo.
> docs: fix readme typo and clarify use of `setId()`

- lib/job.js
We have multiple API instances adding bee-queue jobs.
Our workers call `Job#reportProgress` for long term jobs.
Depending on the API intance handling the call, it might not have the progress update.
I added the progress to the stored job data, same place as the status.
It ensures that the progress is saved properly, and that it is not `0` on a consumer recovering the job from redis.
I hope that it's mergable for you, and if so, I would like to know when a release with this feature is possible, so I know if a fork is needed for my project.
> Feat | Job | Store progress with the whole job data

- README.md
Fixes typo in README `that` -> `than`
> fix: typo fix in README

- lib/defaults.js
- lib/queue.js
- test/queue-test.js
The current behaviour is to retry as fast as possible, leading to a spam of commands and error messages if the redis instance is for example unavailable for a brief period. It seems more sensible to take a bit more care in retrying.
> If the brpoplpush commands fails, wait before retrying

- lib/lua/raiseDelayedJobs.lua
Resubmitting https://github.com/bee-queue/bee-queue/pull/192 from @Tob0t and @mattbornski to rebase and re-run CI checks:
> Since there is no progress on #123 I created another PR.
> 
> FYI: The commit from @mattbornski was taken.
> 
> Since our queues stopped working if there are more than 8k jobs with the same timestamp, we needed a fix asap. I know that the PR was not merged since there could be a further improvements. However as @mattbornski mentioned, better this fix with blocking redis for short time than processing no jobs at all.
> 
> We are already using this code on our production system since we needed a fix asap.
> 
> Disclaimer: I'm not a lua programmer, so feel free to adapt the PR ;)
> fix: queues stop working when there are more than 8k jobs with the same timestamp

- README.md
- index.d.ts
- lib/helpers.js
- lib/queue.js
- test/queue-test.js
Hey, this is a super awesome queue library.
I'm working on a `next.js` project and found that whenever I try to build the project, the build process will failed because `Queue` is try to connect to the redis host for some reasons.
Not sure if it is because the logic of connection to redis host is in the constructor of the `Queue`,  but be able manually connect to redis seems to solve the problem.
So here is the pull request basically allowing user to manual connect to redis by calling `queue.connect()` after `Queue` instance is created. 
- test is added and README is updated accordingly;
- there is also minor code refactor.
> allow manual redis connection

- lib/job.js
- lib/queue.js
- test/queue-test.js
Adds the documented but missing `retrying` event, and adds a `failed:fatal` event that signals that
a job has failed permanently. The `failed` event remains as it was, signaling job execution
failures without signaling the outcome of the job.
Fixes #184; see #186 for more discussion and an alternate proposal.
> feat: add job retrying and failed:fatal events
